baseURL = "https://elstondsouza.com/"
languageCode = "en-us"
title = "Elston D'Souza"
enableInlineShortcodes = true
summarylength = 10
enableEmoji = true
customCss = ["css/blog.css"]
theme="soho"

[params]
copyright = "Elston D'Souza"
license = ""
licenseURL = "https://elstondsouza.com/"
themeColor = "#2B303A"
author = "Elston D'Souza"
profilePicture = "images/cropped.jpg"
math = true 

  [[params.socialIcons]]
  icon = "fa-linkedin"
  title = "Linkedin"
  url = "https://www.linkedin.com/in/elstonndsouza"

  [[params.socialIcons]]
  icon = "fa-github"
  title = "GitHub"
  url = "https://github.com/elston-n-dsouza/"

  [[params.socialIcons]]
  icon = "fa-twitter"
  title = "Twitter"
  url = "https://twitter.com/elston_neil"

	[[params.socialIcons]]
	icon = "fa-orcid"
	url = "https://orcid.org/0000-0002-5394-7260"

[menu]

  [[menu.main]]
  name = "Blog"
  weight = 100
  identifier = "posts"
  url = "/blog/"

	[[menu.main]]
  name = "Publications"
  identifier = "publications"
  weight = 300
  url = "/publications/"

  [[menu.main]]
  name = "About"
  identifier = "about"
  weight = 300
  url = "/about/"

  [[menu.main]]
  name = "Contact"
  identified = "contact"
  weight = 500
  url = "/contact/"

[markup]

  [markup.highlight]
  codeFences = true
  guessSyntax = false
  hl_Lines = ""
  lineNoStart = 1
  lineNos = false
  lineNumbersInTable = true
  noClasses = true # if false, you need to provide you own custom CSS
  style = "monokai"
  tabWidth = 4

[services]
  [services.googleAnalytics]
    ID = "G-70W7G09YNW"
