baseURL = "https://elstondsouza.com/"
languageCode = "en-us"
title = "Elston Neil D'Souza"
relativeURLs = true

## Custom CSS 
customCss = ["css/blog.css"]
#customJs = ["js/blog.js"]

theme="soho"
[params]
copyright = "Elston Neil D'Souza"
license = ""
licenseURL = "https://elstondsouza.com/"
# Color Palette https://coolors.co/0b3954-bfd7ea-ff6664-e0ff4f-fefffe
themeColor = "#0b3954"
author = "Elston D'Souza"
profilePicture = "images/cropped.jpg"
math = true 

  [[params.socialIcons]]
  icon = "fa-linkedin"
  title = "Linkedin"
  url = "https://www.linkedin.com/in/elstonndsouza"

  [[params.socialIcons]]
  icon = "fa-github"
  title = "GitHub"
  url = "https://github.com/elston-n-dsouza/"

  [[params.socialIcons]]
  icon = "fa-twitter"
  title = "Twitter"
  url = "https://twitter.com/elston_neil"

	[[params.socialIcons]]
	icon = "fa-orcid"
	url = "https://orcid.org/0000-0002-5394-7260"
[menu]

  [[menu.main]]
  name = "Blog"
  weight = 100
  identifier = "posts"
  url = "/blog/"

	[[menu.main]]
  name = "Publications"
  identifier = "publications"
  weight = 300
  url = "/publications/"

  [[menu.main]]
  name = "About"
  identifier = "about"
  weight = 300
  url = "/about/"

  [[menu.main]]
  name = "Contact"
  identified = "contact"
  weight = 500
  url = "/contact/"
